### ISSUE TITLE
简直离谱

### ISSUE THREAD

**Issue by maybe-why-not** [wgpsec/DBJ#17]
ip资产梳理导入了几个ip，结果目录扫描攻击了一大堆未知域名和ip，相差十万八千里

**Comment by wintrysec** [comment]
你确定导入的IP不是CDN？自己手动FOFA一下看看结果是不是一大堆未知域名和ip

**Comment by wintrysec** [comment]
> 图我是不敢截了，都梭哈到哪去了，作者好好检查一下
> ![image](https://user-images.githubusercontent.com/29968903/121491711-ca72c380-ca08-11eb-9304-e709f601ba73.png)

找到问题原因了，下任务的时候行尾有空行或者换行符，这样就会之际把domain=""的前1w条资产导入；
现在已经修复，进行了行尾换行符的检查处理。
