### ISSUE TITLE
希望增加docker部署方式

### ISSUE THREAD

**Issue by wakaka123wakaka** [wgpsec/DBJ#2]

**Comment by wintrysec** [comment]
等完善的差不多了，再加Docker部署方式，现在属于测试阶段

**Comment by zygds** [comment]
@wintrysec docker 部署会有更多的问题，但是采用docker部署一些配置信息都可以替换的
docker-compose.yaml
-e passwd:123456
容器内部只需要使用$passwd
而git每次更新都要去修改配置文件安装依赖有点麻烦
