### ISSUE TITLE
Web资产

### ISSUE THREAD

**Issue by little-2pig** [wgpsec/DBJ#5]
web资产管理的web资产点击后没资产信息显示，好像后台也没进行信息收集呢

**Comment by keac** [comment]
能说明详细点吗

**Comment by little-2pig** [comment]
就是点击web资产，后台没有获取数据的动作，然后web也没数据






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wgpsec/DBJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wgpsec/DBJ] Web资产 (#5)





 
能说明详细点吗

**Comment by wintrysec** [comment]
> web资产管理的web资产点击后没资产信息显示，好像后台也没进行信息收集呢

任务格式可能下错了，后台有报错没；你的任务截图和后台错误信息截图发下；记得关键部分打码；

**Comment by little-2pig** [comment]
Web资产添加任务后，点击查看子域名和资产，后台并没报错也没任务进行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wgpsec/DBJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wgpsec/DBJ] Web资产 (#5)





  
web资产管理的web资产点击后没资产信息显示，好像后台也没进行信息收集呢
  
任务格式可能下错了，后台有报错没；你的任务截图和后台错误信息截图发下；记得关键部分打码；

**Comment by wintrysec** [comment]
我今天也遇到了这个问题，排查后是直连网络不能访问FOFA，挂代理才能访问FOFA
