### ISSUE TITLE
whois反查会封ip这块是怎么解决的

### ISSUE THREAD

**Issue by laowang1026** [wgpsec/DBJ#7]
whois反查会封ip这块是怎么解决的

**Comment by wintrysec** [comment]
X-Remote-Addr

**Comment by laowang1026** [comment]
<img width="1123" alt="WX20210407-225310@2x" src="https://user-images.githubusercontent.com/45323129/113887535-28f6a800-97f4-11eb-878b-ef46d58985f8.png">
我从代码里面并没有看见X-Remote-Addr，百度的我看见X-Remote-Addr了
