### ISSUE TITLE
我安装依赖报下面的错误，怎么办？

### ISSUE THREAD

**Issue by chenmonster** [wgpsec/DBJ#8]
已经安装了vs2019，但是执行下面的命令安装到 pycryptodome 报错

```bash
pip install -r requirements.txt
```

![image](https://user-images.githubusercontent.com/34160512/113272972-c0e52500-930e-11eb-85f6-1e1c7fd5f476.png)

**Comment by wintrysec** [comment]
pycryptodome 模块按不上的话，根据你的python版本去百度一下，跟vs2019没得关系
